### PR TITLE
Scala 2.12.8

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by ennru** [comment]
The compilation error is a regression in Scala 2.12.8: https://github.com/scala/bug/issues/11305

**Comment by 2m** [comment]
The linked bug fix is targeted for 2.12.9. Lets wait for that and skip 2.12.8.

**Comment by 2m** [comment]
ftp connector does not compile with Scala 2.13.0-M5, with the same error.
